### ISSUE TITLE
Angular 16 Not Supported

### ISSUE THREAD

**Issue by neodescis** [haavardj/ngx-cron-editor#16]
Can we add support for Angular 16? Happy to submit a pull request if it would help. Not sure whether it's preferable to upgrade the project or just bump support in the package's peer dependencies.

**Comment by haavardj** [comment]
Yes we can :-) Please submit a pull request. I have been rather busy lately, but hopefully I can merge a PR quickly.

**Comment by haavardj** [comment]
Angular 16 support is available from version 0.7.8.
