### ISSUE TITLE
Previous Angular versions compatability

### ISSUE THREAD

**Issue by haavardj** [haavardj/ngx-cron-editor#20]
Could you please make it compatible with previous Angular versions (Angular 12)?

_Originally posted by @bhardwajvinay004 in https://github.com/haavardj/ngx-cron-editor/issues/15#issuecomment-1680329690_

**Comment by haavardj** [comment]
@bhardwajvinay004 Please let me know what the specific issues are?

Maintaining and checking backward compatibility is a pain for Angular apps. I was hoping to avoid it. I was planning to cut old angular versions from peer dependencies as we are probably not compatible very far back.

**Comment by bhardwajvinay004** [comment]
@haavardj Facing below error:
![ngx-cron-editor_compatibility_issue](https://github.com/haavardj/ngx-cron-editor/assets/44772691/f9171130-2898-4755-a768-049124b35e0d)



> @bhardwajvinay004 Please let me know what the specific issues are?
> 
> Maintaining and checking backward compatibility is a pain for Angular apps. I was hoping to avoid it. I was planning to cut old angular versions from peer dependencies as we are probably not compatible very far back.


@haavardj

**Comment by sbond12** [comment]
We would greatly benefit if you could get the current version to be backward compatible with the pre-Material version of the editor.

**Comment by haavardj** [comment]
> We would greatly benefit if you could get the current version to be backward compatible with the pre-Material version of the editor.

Unfortunately, maintaining backward compatibility is not something I can prioritize anytime soon. If anyone volunteers to do this, I will be more than happy to make it happen.
