### ISSUE TITLE
Build issues with ngx-cron-editor 0.7.9 with Angular 15.2.9

### ISSUE THREAD

**Issue by sbond12** [haavardj/ngx-cron-editor#24]
Hello,

All @angular/xxxx are at 15.2.9 including:
  "@angular/material": "^15.2.9",
  "@angular/cdk": "^15.2.9",
  "typescript": "~4.9.5",
  "ts-node": "~9.0.0",
  "tslib": "~2.4.0",
  "bootstrap": "~4.5.3",
  "@ng-bootstrap/ng-bootstrap": "~8.0.0",

I'm including these modules:
    CommonModule,
    BrowserModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    BrowserAnimationsModule,
    MatCardModule,
    MatSelectModule,
    MatSliderModule,
    MatGridListModule,
    MatMenuModule,
    MatIconModule,
    MatButtonModule,
    LayoutModule,
    CronEditorModule,
    MatInputModule,
    MatListModule,
    MatButtonToggleModule

Building with ngx-cron-editor ~0.7.9 and I'm getting the following errors:

Error: node_modules/ngx-cron-editor/src/cron-editor.component.d.ts:106:84 - error TS2344: Type '{ backgroundColor: { alias: "backgroundColor"; required: false; }; color: { alias: "color"; required: false; }; disabled: { alias: "disabled"; required: false; }; options: { alias: "options"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"backgroundColor"' is incompatible with index signature.
    Type '{ alias: "backgroundColor"; required: false; }' is not assignable to type 'string'.

106     static ɵcmp: i0.ɵɵComponentDeclaration<CronGenComponent, "cron-editor", never, { "backgroundColor": { "alias": "backgroundColor"; "required": false; }; "color": { "alias": "color"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "options": { "alias": "options"; "required": false; }; }, {}, never, never, false, never>;

Error: node_modules/ngx-cron-editor/src/cron-time-picker.component.d.ts:25:92 - error TS2344: Type '{ disabled: { alias: "disabled"; required: false; }; use24HourTime: { alias: "use24HourTime"; required: false; }; hideHours: { alias: "hideHours"; required: false; }; hideMinutes: { alias: "hideMinutes"; required: false; }; hideSeconds: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"disabled"' is incompatible with index signature.
    Type '{ alias: "disabled"; required: false; }' is not assignable to type 'string'.

25     static ɵcmp: i0.ɵɵComponentDeclaration<TimePickerComponent, "cron-time-picker", never, { "disabled": { "alias": "disabled"; "required": false; }; "use24HourTime": { "alias": "use24HourTime"; "required": false; }; "hideHours": { "alias": "hideHours"; "required": false; }; "hideMinutes": { "alias": "hideMinutes"; "required": false; }; "hideSeconds": { "alias": "hideSeconds"; "required": false; }; }, {}, never, never, false, never>; 

Can you please offer some help as to why I'm getting these error?  Thanks in advance.

**Comment by sudhakar-sekar** [comment]
Hello @sbond12 ,

Am also using Angular version 15.2.9 and facing this issue. Did you find any solution for this?

**Comment by haavardj** [comment]
Did you figure this out? I believe I had these errors at some point, but they disappeared when updating the repository.

**Comment by lesauf** [comment]
It is a matter of compatibility with Angular packages. For me, on Angular 14 the version that worked was 0.7.4.

Either you upgrade your project to latest Angular or you find an old version that work with your Angular version.

**Comment by haavardj** [comment]
Yes. I believe this is the only way to deal with Angular incompatibilities and bugs: updating your project. I will hopefully have time soon to move the repo to Angular 17. I will also remove the older Angular from the peer dependencies list.
