### ISSUE TITLE
Internationalization support.

### ISSUE THREAD

**Issue by sstinson91** [haavardj/ngx-cron-editor#25]
This isn't so much an issue, more of a question - I'm using Angular's built in i18n for internationalization. I was wondering if there is a way to modifying the label text (e.g. hourly, weekly, monthly etc.) so I can localize the cron editor.

**Comment by haavardj** [comment]
i18n was not trivial to add for Angular libraries, but you can find an initial stab in the 25-internationalization-support branch. Let me know if you have issues, and feel free to add translations. 

I will merge into master and release in a few days if everything works out.
