### ISSUE TITLE
Cron expression generated as null for minutes tab.

### ISSUE THREAD

**Issue by raBot1994** [haavardj/ngx-cron-editor#26]
Hi,

On the minutes tab, the default value that loads on the dropdown is 1. 

![image](https://github.com/haavardj/ngx-cron-editor/assets/127442378/a9658c29-1107-4d6d-aea5-d2ada815cbe4)

If I not change this (triggering the onChange function of the dropdown) , the resulting cron expression is generated as null. 

If I click on the dropdown and change the value from 1 -> 3 and then back to 1. (Which is guess is triggering an event) , then the cron expression is generated properly. 

Is there any workaround for this? 

```
{
    formInputClass: 'form-control cron-editor-input',
    formSelectClass: 'form-control cron-editor-select',
    formRadioClass: 'cron-editor-radio',
    formCheckboxClass: 'cron-editor-checkbox',

    defaultTime: '00:00:00',

    hideMinutesTab: false,
    hideHourlyTab: false,
    hideDailyTab: false,
    hideWeeklyTab: false,
    hideMonthlyTab: false,
    hideYearlyTab: false,
    hideAdvancedTab: true,
    hideSpecificWeekDayTab: false,
    hideSpecificMonthWeekTab: false,

    use24HourTime: true,
    hideSeconds: true,

    cronFlavor: 'standard',
  }
```

**Comment by haavardj** [comment]
I`m not sure this is a bug or a feature, but ngx-cron-editor@0.7.10 will now set days to * when no specific day is set.

**Comment by haavardj** [comment]
@raBot1994 Can you please verify that you have the most up-to-date version of the editor? From the screenshot, it seems like you are using an old one.
