### ISSUE TITLE
Bundle index file is missing

### ISSUE THREAD

**Issue by Aleksey-Yermolenko** [haavardj/ngx-cron-editor#30]
In v.0.8.0 file index.d.ts is missing, so ng cli fails to build projects because it cannot resolve package's exported API with:

`import { CronOptions } from 'ngx-cron-editor';`

Works:
`import { CronOptions } from 'ngx-cron-editor/public_api';`

**Comment by haavardj** [comment]
Seems like a build error. I just pushed out 0.8.1. Please check if that works better.
