### ISSUE TITLE
Not building/compile solution on 0.8.2 version in angular 15

### ISSUE THREAD

**Issue by nirajdangi7j86** [haavardj/ngx-cron-editor#36]
I have install "ngx-cron-editor": "^0.8.2" in my angular 15.1.0 project and configure this control. But solution is not building/compile successfully. I am getting  TS2344: Type error, attached the error image, Can anyone help me on this? 
![image](https://github.com/haavardj/ngx-cron-editor/assets/169381201/fb5a03e1-0b8d-4edc-aee4-ea23c8567e3d)

**Comment by nirajdangi7j86** [comment]
Error in cron-editor.component.d and cron-time-picker.component.d files.

**Comment by haavardj** [comment]
Since we are now targeting Angular 18, supporting 15 is unfortunately not on my tasklist :-) But if you have a fix, please upen a PR. But I thing you are probably better off updating your project to the newest Angular version. s
