### ISSUE TITLE
Not Compatible with Angular 18

### ISSUE THREAD

**Issue by VSO-Dev5000** [haavardj/ngx-cron-editor#37]
The current dependencies prevent from installing Angular 18. By forcing the Angular 18 update, the library still works fine.

![image](https://github.com/haavardj/ngx-cron-editor/assets/150812663/a2e2365c-5206-4b17-9c3a-4c1220cb426b)

**Comment by ahmadalsadder** [comment]
@VSO-Dev5000  Have you found any solution regarding this ?

**Comment by haavardj** [comment]
Let me know if pr #41 does break anything.

**Comment by themadprofessor** [comment]
It appears the import has changed from
```
import { CronEditorModule } from 'ngx-cron-editor';
```
to
```
import { CronEditorModule } from "ngx-cron-editor/src/cron-editor.module";
```

**Comment by haavardj** [comment]
That doesn't look right... We use the first one in the demo app. 

> It appears the import has changed from
> 
> ```
> import { CronEditorModule } from 'ngx-cron-editor';
> ```
> 
> to
> 
> ```
> import { CronEditorModule } from "ngx-cron-editor/src/cron-editor.module";
> ```
